name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-north-1'  # Replace with your region
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-external-id: ${{ secrets.AWS_EXTERNAL_ID }} # Optional, only if required by the trust policy

    - name: Deploy to Amazon ECS
      run: |
        # Commands to deploy, for example:
        aws ecs update-service --cluster MyCluster --service MyService --force-new-deployment
